### ISSUE TITLE
Releasing evaluation datasets?

### ISSUE THREAD

**Issue by vishaal27** [HanSolo9682/CounterCurate#1]
Hey, thanks for your great work!
I am very interested in playing around with the two evaluation datasets you introduced in your work: `Flickr30kPositions-Test` and `PointQA-LookTwice-Counting-Test`. Is there a timeline for releasing those datasets?
Thanks again!

**Comment by HanSolo9682** [comment]
Hi, thank you for your support! I plan to start cleaning up my code for data curation starting later this week. As a reminder, for both of these datasets, you will have to download the required data (images, captions, etc.) from the respective authors' sources. We will only release the code that is used to generate the dataset from the author's data.

**Comment by vishaal27** [comment]
Ok great, could you please point me to the original links for downloading both these datasets so that I can set them up before you release your data curation code? That would enable me to be more efficient once you do release :)
Thanks!

**Comment by HanSolo9682** [comment]
Hi, I have just added in the readme for you to download the two datasets from the original authors.
