### ISSUE TITLE
About the generation of the negative captions 

### ISSUE THREAD

**Issue by Caroline-6** [HanSolo9682/CounterCurate#3]
Hi, this a great work. I am very interested in the part of using the GPT-4V to generate hard negative captions. Would you like to release the related code or describe more details about the process?

**Comment by HanSolo9682** [comment]
Hi, thank you for your feedback. The relate code you're asking is the file `datasets/gpt4v_prompt_gen.py`. As described in the paper, we guide GPT4V with a prompt (which you can find both in the file and in the Appendix), the original image, and an image with all the bounding boxes of each object (code at `datasets/mark_img.py`).

**Comment by Caroline-6** [comment]
oh,ok. I see. thank you!
